### ISSUE TITLE
Mac compatibility?

### ISSUE THREAD

**Issue by adamcarter1** [dubhater/vapoursynth-dedot#2]
Any chance you could extend compatibility to mac and/or linux. Thank you

**Comment by dubhater** [comment]
It's supposed to work already. I did all the testing in Linux. Did you encounter an error?

**Comment by adamcarter1** [comment]
Oh i realized my error. Go ahead and close this sorry, and thanks for the quick response,

**Comment by adamcarter1** [comment]
Oh i realized my error. Go ahead and close this sorry, and thanks for the quick response,

**Comment by adamcarter1** [comment]
Oh i realized my error. Go ahead and close this sorry, and thanks for the quick response,

**Comment by adamcarter1** [comment]
Oh i realized my error. Go ahead and close this sorry, and thanks for the quick response,

**Comment by adamcarter1** [comment]
Oh i realized my error. Go ahead and close this sorry, and thanks for the quick response,

**Comment by adamcarter1** [comment]
Oh i realized my error. Go ahead and close this sorry, and thanks for the quick response,

**Comment by adamcarter1** [comment]
Oh i realized my error. Go ahead and close this sorry, and thanks for the quick response,

**Comment by adamcarter1** [comment]
Oh i realized my error. Go ahead and close this sorry, and thanks for the quick response,

**Comment by adamcarter1** [comment]
Oh i realized my error. Go ahead and close this sorry, and thanks for the quick response,

**Comment by adamcarter1** [comment]
Oh i realized my error. Go ahead and close this sorry, and thanks for the quick response,

**Comment by adamcarter1** [comment]
Oh i realized my error. Go ahead and close this sorry, and thanks for the quick response,

**Comment by adamcarter1** [comment]
Oh i realized my error. Go ahead and close this sorry, and thanks for the quick response,

**Comment by adamcarter1** [comment]
Oh i realized my error. Go ahead and close this sorry, and thanks for the quick response,
